local LSM = LibStub("LibSharedMedia-3.0")

--------- Random Sounds --------
LSM:Register("sound", "|cff00eaffDark Souls Death|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z1_DarkSouls_Death.mp3]])
LSM:Register("sound", "|cff00eaffSkill Issue|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z2_Skillissue.ogg]])
LSM:Register("sound", "|cff00eaffJurrasic Park|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z3_JurassicPark.ogg]])
LSM:Register("sound", "|cff00eaffMega Pint|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z4_MegaPint.mp3]])
LSM:Register("sound", "|cff00eaffDaddy Chill|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z5_DaddyChill.mp3]])
LSM:Register("sound", "|cff00eaffTaDa|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z6_TaDa.mp3]])
LSM:Register("sound", "|cff00eaffZelda Chest|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z7_ZeldaChest.mp3]])
LSM:Register("sound", "|cff00eaffPedro|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z8_Pedro.mp3]])
LSM:Register("sound", "|cff00eaffSurf Bird|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z9_SurfBird.mp3]])
LSM:Register("sound", "|cff00eaffAnother One|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z10_AnotherOne.mp3]])
LSM:Register("sound", "|cff00eaffCoffin Dance|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z11_CoffinDance.mp3]])
LSM:Register("sound", "|cff00eaffWhy Are You Running|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z12_WhyAreYouRunning.mp3]])
LSM:Register("sound", "|cff00eaffPhasmoVan|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z13_PhasmoVan.mp3]])
LSM:Register("sound", "|cff00eaffUwU|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\default\Z14_UwU.mp3]])
LSM:Register("sound", "|cff00eaffDark Souls Death|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z1_DarkSouls_Death.mp3]])
LSM:Register("sound", "|cff00eaffSkill Issue|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z2_SKillIssue.ogg]])
LSM:Register("sound", "|cff00eaffJurassic Park|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z3_JurassicPark.ogg]])
LSM:Register("sound", "|cff00eaffMega Pint|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z4_MegaPint.mp3]])
LSM:Register("sound", "|cff00eaffDaddy Chill|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z5_DaddyChill.mp3]])
LSM:Register("sound", "|cff00eaffTaa Daa|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z6_TaDa.mp3]])
LSM:Register("sound", "|cff00eaffZelda Chest|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z7_ZeldaChest.mp3]])
LSM:Register("sound", "|cff00eaffPedro|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z8_Pedro.mp3]])
LSM:Register("sound", "|cff00eaffSurf Bird|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z9_SurfBird.mp3]])
LSM:Register("sound", "|cff00eaffAnother One|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z10_AnotherOne.mp3]])
LSM:Register("sound", "|cff00eaffCoffin Dance|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z11_CoffinDance.mp3]])
LSM:Register("sound", "|cff00eaffWhy are you running?|r",
    [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z12_WhyAreYouRunning.mp3]])
LSM:Register("sound", "|cff00eaffPhasomo Van|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z13_PhasmoVan.mp3]])
LSM:Register("sound", "|cff00eaffUwU|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\Z14_UwU.mp3]])
LSM:Register("sound", "|cff00eaffSigma|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\what_the_sigma.mp3]])
LSM:Register("sound", "|cff00eaffViolin Effect|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\violin_screech.mp3]])
LSM:Register("sound", "|cff00eaffVine Boom|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\vine_boom.mp3]])
LSM:Register("sound", "|cff00eaffGrim Batol|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\grim_batol.mp3]])
LSM:Register("sound", "|cff00eaffHonk Shoo|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\sleep_meme.mp3]])
LSM:Register("sound", "|cff00eaffRizz|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\rizz.mp3]])
LSM:Register("sound", "|cff00eaffJeff|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\name_jeff.mp3]])
LSM:Register("sound", "|cff00eaffRehehehe|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\rehehehe.mp3]])
LSM:Register("sound", "|cff00eaffRaagh|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\raagh.mp3]])
LSM:Register("sound", "|cff00eaffPlug|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\pluh.mp3]])
LSM:Register("sound", "|cff00eaffOmg Bruh|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\omg_bruh.mp3]])
LSM:Register("sound", "|cff00eaffOke|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\oke.mp3]])
LSM:Register("sound", "|cff00eaffBruh|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\bruh.mp3]])
LSM:Register("sound", "|cff00eaffLebron James|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\lebron.mp3]])
LSM:Register("sound", "|cff00eaffHuh|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\huh.mp3]])
LSM:Register("sound", "|cff00eaffGoddamn|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\goddamn.mp3]])
LSM:Register("sound", "|cff00eaffWhat the dog doin?|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\dog_doin.mp3]])
LSM:Register("sound", "|cff00eaffBrainrot Fart|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\brainrot_fart.mp3]])
LSM:Register("sound", "|cff00eaffAugh|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\augh.mp3]])
LSM:Register("sound", "|cff00eaffFart Reverb|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\fart_reverb.mp3]])
LSM:Register("sound", "|cff00eaffFart 1|r", [[Interface\Addons\SharedMedia_Pixelbased\sound\default\fart_1.mp3]])

----------- Guild Raider Sounds --------
LSM:Register("sound", "|cff00eaffBob Lunker|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\bob_lunker.mp3]])
LSM:Register("sound", "|cff00eaffEspen Borf|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\espen_bark.mp3]])
LSM:Register("sound", "|cff00eaffIgor AAA|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\igor_scream.mp3]])
LSM:Register("sound", "|cff00eaffKyth HUAGH|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\kyth_huh.mp3]])
LSM:Register("sound", "|cff00eaffMike Uh Oh|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\mike_uhoh.mp3]])
LSM:Register("sound", "|cff00eaffPeba Gooning|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\peba_gooning.mp3]])
LSM:Register("sound", "|cff00eaffMike Balling|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\mike_balling.mp3]])
LSM:Register("sound", "|cff00eaffRalegh Aughh|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\ralegh_augh.mp3]])
LSM:Register("sound", "|cff00eaffBob Dying|r", [[Interface\AddOns\SharedMedia_Pixelbased\sound\bob_dying.mp3]])


